/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarketproject;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author N A N A
 */
public class Products extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
     ArrayList<Market>  supermarket=new ArrayList();
   //ArrayList<TableModelObserver> observers = new ArrayList<>();
    public void Arraylist(){
       
    supermarket.add(new Market("meat","300","2023","6/2023","le","10"));
    supermarket.add(new Market("fruit","20","2023","5/2023","le","11"));
    supermarket.add(new Market("vegtables","15","2023","5/2023","le","12"));
    supermarket.add(new Market("desserts","50","2023","2024","le","13"));
    
    }
   
    public Products() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Productsl = new javax.swing.JLabel();
        namel = new javax.swing.JLabel();
        pricel = new javax.swing.JLabel();
        idl = new javax.swing.JLabel();
        yearl = new javax.swing.JLabel();
        manufacturerl = new javax.swing.JLabel();
        datel = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        pricetf = new javax.swing.JTextField();
        idTf = new javax.swing.JTextField();
        yearTf = new javax.swing.JTextField();
        manufacturerTf = new javax.swing.JTextField();
        dateTf = new javax.swing.JTextField();
        addb = new javax.swing.JButton();
        removeb = new javax.swing.JButton();
        closeb = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        searchL = new javax.swing.JLabel();
        searchTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 587));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Productsl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Productsl.setForeground(new java.awt.Color(255, 255, 255));
        Productsl.setText("Products");

        namel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namel.setForeground(new java.awt.Color(255, 255, 255));
        namel.setText("Name");

        pricel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pricel.setForeground(new java.awt.Color(255, 255, 255));
        pricel.setText("Price");

        idl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idl.setForeground(new java.awt.Color(255, 255, 255));
        idl.setText("ProductID");

        yearl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        yearl.setForeground(new java.awt.Color(255, 255, 255));
        yearl.setText("Year of production");

        manufacturerl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manufacturerl.setForeground(new java.awt.Color(255, 255, 255));
        manufacturerl.setText("Manufacturer");

        datel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        datel.setForeground(new java.awt.Color(255, 255, 255));
        datel.setText("Expiration date");
        datel.setToolTipText("");

        nametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametfActionPerformed(evt);
            }
        });
        nametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nametfKeyPressed(evt);
            }
        });

        pricetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricetfActionPerformed(evt);
            }
        });
        pricetf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pricetfKeyPressed(evt);
            }
        });

        idTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTfKeyPressed(evt);
            }
        });

        yearTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                yearTfKeyPressed(evt);
            }
        });

        manufacturerTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturerTfActionPerformed(evt);
            }
        });
        manufacturerTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                manufacturerTfKeyPressed(evt);
            }
        });

        dateTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateTfKeyPressed(evt);
            }
        });

        addb.setText("Add");
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });

        removeb.setText("Remove");
        removeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebActionPerformed(evt);
            }
        });

        closeb.setText("Close");
        closeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"meat", "400$", "2023", "30/7/2023", "Bedaya", "222222"},
                {"fruit", "50$", "2023", "30/7/2023", "Unity", "222233"},
                {"vegetables", "40$", "2023", "30/7/2023", "Unity", "222244"},
                {"dessert", "150$", "2023", "30/7/2023", "Classique", "222255"},
                {"juices", "25$", "2023", "30/7/2023", "Juhayna", "222266"},
                {"Cheese", "100$", "2023", "30/7/2023", "Domety", "222277"}
            },
            new String [] {
                "product", "price", "year of production", "expire date", "manufucturer", "Item ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        searchL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchL.setForeground(new java.awt.Color(255, 255, 255));
        searchL.setText("Search");

        searchTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTfKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(422, 422, 422)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(manufacturerTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pricetf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pricel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearl)
                                    .addComponent(manufacturerl)
                                    .addComponent(datel)
                                    .addComponent(searchL, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(138, 138, 138)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(addb)
                                .addGap(100, 100, 100)
                                .addComponent(removeb)
                                .addGap(202, 202, 202)
                                .addComponent(closeb)))
                        .addContainerGap(433, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(Productsl, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Productsl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namel)
                            .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pricel)
                            .addComponent(pricetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idl)
                    .addComponent(idTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearl)
                    .addComponent(yearTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturerl)
                    .addComponent(manufacturerTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datel)
                    .addComponent(dateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchL)
                    .addComponent(searchTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addb)
                    .addComponent(removeb)
                    .addComponent(closeb))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed
        // TODO add your handling code here:
        if(pricetf.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "PLEASE enter all data");
        }else{
        String price =pricetf.getText();
        double priceee=Double.parseDouble(price);
        
        boolean flag =true;
        
       if(priceee<=0){
           JOptionPane.showMessageDialog(this, "Please enter a price number greater than 0", "price", JOptionPane.ERROR_MESSAGE);
      flag=false;
      Products pp=new Products();
      pp.show();
      dispose();
       }
       if(flag){
        if( nametf.getText().isEmpty() || pricetf.getText().isEmpty() ||idTf.getText().isEmpty()||yearTf.getText().isEmpty()||manufacturerTf.getText().isEmpty()||dateTf.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "PLEASE enter all data");
        }else{
          //  String data[]={jTextField1.getText(),jTextField2.getText()};
            supermarket.add(new Market(nametf.getText(),pricetf.getText(),idTf.getText(),yearTf.getText(),manufacturerTf.getText(),dateTf.getText()));
         DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
         String rowData[] = {nametf.getText(),pricetf.getText(),idTf.getText(),yearTf.getText(),manufacturerTf.getText(),dateTf.getText()};
   model.addRow(rowData);
            DefaultTableModel table =(DefaultTableModel)jTable2.getModel();
           // for (int i = 0; i < jTable2.getRowCount(); i++) {
     // jTable2.editCellAt(ERROR, jTable2.getColumnCount());
     // jTable2.
           // }
        JOptionPane.showMessageDialog((this), "Added successfuly");
        nametf.setText("");
        pricetf.setText("");
        idTf.setText("");
        
        yearTf.setText("");
        manufacturerTf.setText("");
        dateTf.setText("");
        }
       }
       }
    }//GEN-LAST:event_addbActionPerformed

    private void removebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebActionPerformed
        // TODO add your handling code here:
      DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
      model.removeRow(jTable2.getSelectedRow());
        JOptionPane.showMessageDialog((this), "Removed successfuly");
        
       
    }//GEN-LAST:event_removebActionPerformed
    
    private void closebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebActionPerformed
        // TODO add your handling code here:
        Exit e = new Exit();
        e.show();
        dispose();
    }//GEN-LAST:event_closebActionPerformed

    private void manufacturerTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturerTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturerTfActionPerformed

    private void pricetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricetfActionPerformed

    private void idTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTfKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            idTf.setEditable(false);
            JOptionPane.showMessageDialog(this, "enter numbers only", "ID", JOptionPane.ERROR_MESSAGE);
        }else{
            idTf.setEditable(true);
        }
    }//GEN-LAST:event_idTfKeyPressed

    private void pricetfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pricetfKeyPressed
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            pricetf.setEditable(false);
            JOptionPane.showMessageDialog(this, "enter numbers only", "Price", JOptionPane.ERROR_MESSAGE);
        }else{
            pricetf.setEditable(true);
        }
    }//GEN-LAST:event_pricetfKeyPressed

    private void manufacturerTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manufacturerTfKeyPressed
        // TODO add your handling code here:
            char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            manufacturerTf.setEditable(true);
            }else{
           manufacturerTf.setEditable(false);
            JOptionPane.showMessageDialog(this, "enter letters only", "manufucturer", JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_manufacturerTfKeyPressed

    private void dateTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateTfKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            dateTf.setEditable(false);
            JOptionPane.showMessageDialog(this, "enter numbers only", "Date", JOptionPane.ERROR_MESSAGE);
        }else{
            dateTf.setEditable(true);
        }
    }//GEN-LAST:event_dateTfKeyPressed

    private void nametfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametfKeyPressed
        // TODO add your handling code here:
              char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            nametf.setEditable(true);
            }else{
          nametf.setEditable(false);
            JOptionPane.showMessageDialog(this, "enter letters only", "Name", JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_nametfKeyPressed

    private void yearTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearTfKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            dateTf.setEditable(false);
            JOptionPane.showMessageDialog(this, "enter numbers only", "year", JOptionPane.ERROR_MESSAGE);
        }else{
            dateTf.setEditable(true);
        }
    }//GEN-LAST:event_yearTfKeyPressed

    private void searchTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTfKeyPressed
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        jTable2.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchTf.getText().trim() ));
    }//GEN-LAST:event_searchTfKeyPressed

    private void nametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Productsl;
    private javax.swing.JButton addb;
    private javax.swing.JButton closeb;
    private javax.swing.JTextField dateTf;
    private javax.swing.JLabel datel;
    private javax.swing.JTextField idTf;
    private javax.swing.JLabel idl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField manufacturerTf;
    private javax.swing.JLabel manufacturerl;
    private javax.swing.JLabel namel;
    private javax.swing.JTextField nametf;
    private javax.swing.JLabel pricel;
    private javax.swing.JTextField pricetf;
    private javax.swing.JButton removeb;
    private javax.swing.JLabel searchL;
    private javax.swing.JTextField searchTf;
    private javax.swing.JTextField yearTf;
    private javax.swing.JLabel yearl;
    // End of variables declaration//GEN-END:variables


}
